# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_median <- function(clip, median) {
    .Call(`_ProFound_get_median`, clip, median)
}

subset_cpp_inplace <- function(image = 0L, scol = 1L, ecol = 1L, srow = 1L, erow = 1L, coffset = 0L, roffset = 0L, oimage = 0L) {
    invisible(.Call(`_ProFound_subset_cpp_inplace`, image, scol, ecol, srow, erow, coffset, roffset, oimage))
}

subset_cpp_inplaceI <- function(image = 0L, scol = 1L, ecol = 1L, srow = 1L, erow = 1L, coffset = 0L, roffset = 0L, oimage = 0L) {
    invisible(.Call(`_ProFound_subset_cpp_inplaceI`, image, scol, ecol, srow, erow, coffset, roffset, oimage))
}

adacsFindSkyCellValuesC <- function(image, objects, mask, loc1, loc2, box1, box2, boxadd1, boxadd2, skypixmin, boxiters) {
    .Call(`_ProFound_adacsFindSkyCellValuesC`, image, objects, mask, loc1, loc2, box1, box2, boxadd1, boxadd2, skypixmin, boxiters)
}

adacsFindSkyCellValuesBoxC <- function(image, objects, mask, loc1, loc2, box1, box2, boxadd1, boxadd2, skypixmin, boxiters) {
    .Call(`_ProFound_adacsFindSkyCellValuesBoxC`, image, objects, mask, loc1, loc2, box1, box2, boxadd1, boxadd2, skypixmin, boxiters)
}

adacsmagclip <- function(x, sigma, clipiters, sigmasel, estimate) {
    .Call(`_ProFound_adacsmagclip`, x, sigma, clipiters, sigmasel, estimate)
}

adacsmagclipV <- function(x, sigma, clipiters, sigmasel, estimate) {
    .Call(`_ProFound_adacsmagclipV`, x, sigma, clipiters, sigmasel, estimate)
}

interpolateAkimaGrid <- function(xseq, yseq, tempmat_sky, output) {
    invisible(.Call(`_ProFound_interpolateAkimaGrid`, xseq, yseq, tempmat_sky, output))
}

water_cpp <- function(image = 0L, nx = 1L, ny = 1L, abstol = 1, reltol = 0, cliptol = 1000000, ext = 1L, skycut = 0, pixcut = 1L, verbose = FALSE, Ncheck = 1000000L) {
    .Call(`_ProFound_water_cpp`, image, nx, ny, abstol, reltol, cliptol, ext, skycut, pixcut, verbose, Ncheck)
}

.order_cpp <- function(x) {
    .Call(`_ProFound_order_cpp`, x)
}

.tabulate_cpp <- function(x, max) {
    .Call(`_ProFound_tabulate_cpp`, x, max)
}

water_cpp_old <- function(image = 0L, nx = 1L, ny = 1L, abstol = 1, reltol = 0, cliptol = 1000000, ext = 1L, skycut = 0, pixcut = 1L, verbose = FALSE, Ncheck = 1000000L) {
    .Call(`_ProFound_water_cpp_old`, image, nx, ny, abstol, reltol, cliptol, ext, skycut, pixcut, verbose, Ncheck)
}

