// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/bitmatrix.h"
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;


// validate (ensure exported C++ functions exist before calling them)
static int _bitmatrix_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _bitmatrix_RcppExport_registerCCallable() { 
    R_RegisterCCallable("bitmatrix", "_bitmatrix_RcppExport_validate", (DL_FUNC)_bitmatrix_RcppExport_validate);
    return R_NilValue;
}

RcppExport SEXP _rcpp_module_boot_yada();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_yada", (DL_FUNC) &_rcpp_module_boot_yada, 0},
    {"_bitmatrix_RcppExport_registerCCallable", (DL_FUNC) &_bitmatrix_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_bitmatrix(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
